package com.husky.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseScore<M extends BaseScore<M>> extends Model<M> implements IBean {

	public void setSId(java.lang.String sId) {
		set("s_id", sId);
	}
	
	public java.lang.String getSId() {
		return getStr("s_id");
	}
	
	public void setCId(java.lang.String cId) {
		set("c_id", cId);
	}
	
	public java.lang.String getCId() {
		return getStr("c_id");
	}
	
	public void setSScore(java.lang.Integer sScore) {
		set("s_score", sScore);
	}
	
	public java.lang.Integer getSScore() {
		return getInt("s_score");
	}
	
}

