package com.husky.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudent<M extends BaseStudent<M>> extends Model<M> implements IBean {

	public void setSId(java.lang.String sId) {
		set("s_id", sId);
	}
	
	public java.lang.String getSId() {
		return getStr("s_id");
	}
	
	public void setSName(java.lang.String sName) {
		set("s_name", sName);
	}
	
	public java.lang.String getSName() {
		return getStr("s_name");
	}
	
	public void setSBirth(java.lang.String sBirth) {
		set("s_birth", sBirth);
	}
	
	public java.lang.String getSBirth() {
		return getStr("s_birth");
	}
	
	public void setSSex(java.lang.String sSex) {
		set("s_sex", sSex);
	}
	
	public java.lang.String getSSex() {
		return getStr("s_sex");
	}
	
}

