package com.husky.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCourse<M extends BaseCourse<M>> extends Model<M> implements IBean {

	public void setCId(java.lang.String cId) {
		set("c_id", cId);
	}
	
	public java.lang.String getCId() {
		return getStr("c_id");
	}
	
	public void setCName(java.lang.String cName) {
		set("c_name", cName);
	}
	
	public java.lang.String getCName() {
		return getStr("c_name");
	}
	
	public void setTId(java.lang.String tId) {
		set("t_id", tId);
	}
	
	public java.lang.String getTId() {
		return getStr("t_id");
	}
	
}

