package com.husky.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("course", "c_id", Course.class);
		// Composite Primary Key order: c_id,s_id
		arp.addMapping("score", "c_id,s_id", Score.class);
		arp.addMapping("student", "s_id", Student.class);
		arp.addMapping("teacher", "t_id", Teacher.class);
	}
}


