package com.husky.model;

import com.husky.model.base.BaseTeacher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teacher extends BaseTeacher<Teacher> {
	public static final Teacher dao = new Teacher().dao();
}

