server:
  # 应用服务 WEB 访问端口
  port: 8082

mybatis:
  # 下面这些内容是为了让MyBatis映射指定Mybatis的Mapper文件
  mapper-locations: classpath:mappers/*xml
  # 指定Mybatis的实体目录
  type-aliases-package: com.husky.entity
  configuration:
    map-underscore-to-camel-case: true

spring:
  devtools:
    restart:
      # 开启热部署（更改文件后，自动重启）
      enabled: true

  datasource:
    name: school_exercise
    url: jdbc:mysql://39.99.81.240:3306/school_exercise?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: X14Lidx52!yu
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 39.99.81.240 # 指定redis所在的host
    port: 6379 # 指定redis的端口
    password: 741852 # 设置redis密码
    lettuce:
      pool:
        max-active: 8 # 最大连接数
        max-idle: 8 # 最大空闲数
        min-idle: 0 # 最小空闲数
        max-wait: 100ms # 连接等待时间