server:
  # 应用服务 WEB 访问端口
  port: 9801

mybatis:
  # 下面这些内容是为了让MyBatis映射指定Mybatis的Mapper文件
  mapper-locations: classpath:mappers/*xml
  # 指定Mybatis的实体目录
  type-aliases-package: com.husky.entity
  configuration:
    map-underscore-to-camel-case: true
spring:
  application:
    name: service-db
  main:
    allow-circular-references: false #是否可以循环依赖
  devtools:
    restart:
      # 开启热部署（更改文件后，自动重启）
      enabled: true

  datasource:
    name: school_exercise
    url: jdbc:mysql://172.28.76.31:3306/school_exercise?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: X14Lidx52!yu
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 172.28.76.31 # 指定redis所在的host
    port: 6379 # 指定redis的端口
    password: 741852 # 设置redis密码
    lettuce:
      pool:
        max-active: 8 # 最大连接数
        max-idle: 8 # 最大空闲数
        min-idle: 0 # 最小空闲数
        max-wait: 100ms # 连接等待时间


pagehelper:
  # 设置方言，此处指定 MySQL 数据库
  helper-dialect: mysql
  # 是否启动合理化，默认是 false。
  # 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages（最大页数）会查询最后一页。
  # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: true
  # 是否支持接口参数来传递分页参数，默认false
  support-methods-arguments: true
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
  params: count=countSql
  # 默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）
  page-size-zero: true

# xxl-job 定时任务配置
xxl:
  job:
    admin:
      # 多个地址使用,分割
      addresses: http://172.28.76.31:9001/xxl-job-admin
    accessToken: husky.test
    executor:
      appname: xxl-job-executor-${spring.application.name}
      address:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
