server:
  # 应用服务 WEB 访问端口
  port: 8082

mybatis:
  # 下面这些内容是为了让MyBatis映射指定Mybatis的Mapper文件
  mapper-locations: classpath:mappers/*xml
  # 指定Mybatis的实体目录
  type-aliases-package: com.husky.serverdb.mybatis.entity

spring:
  devtools:
    restart:
      # 开启热部署（更改文件后，自动重启）
      enabled: true